### ISSUE TITLE
Submit to Home Assistant Core

### ISSUE THREAD

**Issue by balloob** [gtdiehl/iotawatt_ha#4]
Home Assistant will have a new added focus on energy management in the next release. We're trying to get as many energy related integrations part of core. 

Your integration is great. Would you want to submit it to core? 

Edit: to avoid unnecessary noise, please don't comment with "+1" or similar. Just use the thumbs up reaction on the first post.

**Comment by jherby2k** [comment]
This would be awesome!

**Comment by djhampson** [comment]
Yes please!!!!

**Comment by gtdiehl** [comment]
Yeah I can help clean up the sensor code a bit a submit it

**Comment by balloob** [comment]
That's great. Tag me when you put up the PR and I'll prioritize review 👍

**Comment by skippy-oz** [comment]
That would be great

**Comment by pvizeli** [comment]
Yeah, I think the code is not bad. Open a PR and with some reviews it should be done soon

**Comment by gtdiehl** [comment]
I want to open a PR for Home Assistant though I am concerned about Issue #1

**Comment by gtdiehl** [comment]
I created a PR for the IoTaWatt integration to be added to Home Assistant Core.
https://github.com/home-assistant/core/pull/55364
